version: '3.8'

services:
  database:
    image: mariadb:10.7
    networks:
      - node-network
    volumes:
      - maria-data:/data/db
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-padmin']
      interval: 5s
      retries: 10
    env_file: .env
  node-api:
    build: .
    image: faculty-ms
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - node-network
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
volumes:
  maria-data:
    driver: local
networks:
  node-network:
    driver: bridge
