version: '3.8'

services:
  node-api:
    image: faculty-ms-prod
    container_name: faculty-ms-api-prod
    command: npm run start
  database:
    container_name: faculty-ms-database-prod
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: faculty-ms
      MARIADB_DATABASE: faculty-ms
