version: '3.8'

services:
  database:
    image: mariadb:10.7
    ports:
      - '3307:3307'
    networks:
      - node-network
    volumes:
      - maria-data:/data/db
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-padmin']
      interval: 5s
      retries: 10
    environment:
      MYSQL_TCP_PORT: 3307
  node-api:
    build: .
    image: facluty-ms
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - node-network
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
volumes:
  maria-data:
    driver: local
networks:
  node-network:
    driver: bridge
